---
# tasks\folders.yml

- name: Ensure that the "C:\Scripts" folder is present.
  win_file:
    path: C:\Scripts
    state: directory
- name: Ensure that the "C:\Tools" folder is present.
  win_file:
    path: C:\Tools
    state: directory
- name: copy scripts resources to target machines
  win_copy:
    src: ../../files/Scripts
    dest: C:\
    force: yes
- name: copy PSTools resources to target machines
  win_copy:
    src: ../../files/Tools
    dest: C:\
    force: yes
- name: Ensure that the "C:\Temp" folder is present.
  win_file:
    path: C:\Temp
    state: directory