---
# tasks\rename.yml

- name: Change the hostname to inventory hostname
  vars:
  win_hostname:
    name: "{{ hostvars[inventory_hostname].xs_vm_def.hostname }}"
  register: res
- name: Reboot
  win_reboot:
  when: res.reboot_required