---
# tasks\rename.yml

- name: Change the hostname to inventory hostname
  vars:
  win_hostname:
    name: "{{ host_hostname | default(inventory_hostname) }}"
  register: res
- name: Reboot
  win_reboot:
  when: res.reboot_required